export default {
    'ru': {
        'advantages': 'Преимущества',
        'products': 'Продукция',
        'gallery': 'Фотогалерея',
        'about_us': 'О компании',
        'speed_gates': 'Скоростные проходы',
        'hero_slide1': 'Решение для бизнес-центров',
        'hero_slide2': 'Решение для офисов',
        'hero_slide3': 'Решение для спортивно-развлекательных объектов',
        'hero_slide4': 'Решение для учебных заведений',
        'hero_slide5': 'Решение для транспортных объектов',
        'hero_slide6': 'Решение для банков',
        'advantages': 'Преимущества',
        'touch_free': 'Бесконтактность',
        'safe_passage': 'Безопасность прохода с детьми',
        'passage_of_people': 'Проезд маломобильных групп населения',
        'safety_in_case': 'Безопасность в аварийной ситуации',
        'convenient_luggage': 'Комфортный провоз багажа',
        '5_years_of_warranty': '5 лет гарантии',
        'st-01_speed_gate': 'Скоростной проход ST‑01',
        'st-11_speed_gate': 'Скоростной проход ST‑11',
        'st-02_speed_gate': 'Скоростной проход ST‑02',
        'wmd-06_swing_gate': 'Калитка WMD‑06, ограждение ВН06',
        'prod_slide0__text': 'Скоростной проход ST‑01',
        'prod_slide0__subtext': 'Универсальный скоростной проход с распашными створками',
        'prod_slide1__text': 'Скоростной проход ST‑11',
        'prod_slide1__subtext': 'Компактный скоростной проход с распашными створками',
        'prod_slide2__text': 'Скоростной проход ST‑02',
        'prod_slide2__subtext': 'Скоростной проход с раздвижными створками',
        'prod_slide3__text': 'Калитка WMD‑06',
        'prod_slide3__subtext': 'Автоматическая калитка со створкой из закаленного стекла',
        'prod_slide4__text': 'Ограждение ВН06',
        'prod_slide4__subtext': 'Ограждение из закаленного стекла',
        'sublist_prod_1': 'Универсальный скоростной проход с распашными створками',
        'sublist_prod_2': 'Компактный скоростной проход с распашными створками',
        'sublist_prod_3': 'Скоростной проход с раздвижными створками',
        'sublist_prod_4': 'Калитка и ограждение',
        'watch_video': 'смотреть видео',
        'overview': 'Ракурсы',
        'access': 'Доступ',
        'dimensions': 'Габариты',
        'safety': 'Безопасность',
        'design': 'Исполнение',
        'integration': 'Интеграция',
        'installation_of_additional': 'Установка дополнительного оборудования',
        'dop_slide0__name': 'Биометрические считыватели',
        'dop_slide1__name': 'Пирометр',
        'dop_slide2__name': 'Терминал распознавания лиц Suprema',
        'dop_slide3__name': 'Терминал распознавания лиц ZKTeco',
        'dop_slide4__name': 'Штрихкод',
        'dop_slide5__name': 'Картоприемник',
        'dop_slide0__signature': 'Кронштейн для биометрических считывателей ',
        'dop_slide1__signature': 'Пирометр',
        'dop_slide2__signature': 'Кронштейны для терминалов распознавания лиц Suprema',
        'dop_slide3__signature': 'Терминал распознавания лиц ZKTeco',
        'dop_slide4__signature': 'Стойка для сканера штрихкода',
        'dop_slide5__signature': 'Стойка с картоприемником',
        'gallery': 'Фотогалерея',
        'gallery_slide1': 'Скоростные проходы ST‑01, офис компании Latécoère, Франция',
        'gallery_slide2': 'Скоростные проходы ST‑01, кинотеатр Cinamon Kosmos, Эстония',
        'gallery_slide3': 'Скоростные проходы ST‑01, бизнес-школа Emlyon, Франция',
        'gallery_slide4': 'Скоростные проходы ST‑01, коворкинг SOK, Москва',
        'gallery_slide5': '',
        'gallery_slide6': 'Скоростные проходы ST‑01 в составе системы контроля доступа PERCo, бизнес-центр West East, Одинцово, Московская область',
        'gallery_slide7': '',
        'gallery_slide8': 'Скоростные проходы ST‑01, фитнес-клуб L\'Appart Fitness, Франция',
        'gallery_slide9': 'Скоростные проходы ST-01, офис компании Student Loans Company, Шотландия',
        'gallery_slide10': 'Скоростные проходы ST-01, офис компании PepsiCo, Мексика',
        'gallery_slide11': 'Скоростные проходы ST‑01, жилой комплекс «Мосфильмовский», Москва',
        'gallery_slide12': 'Скоростные проходы ST‑01 и калитки WMD‑06, Назарбаев Университет, Нур-Султан',
        'gallery_slide13': 'Калитки WMD‑06, детский игровой комплекс KABONK, Нидерланды',
        'gallery_slide14': 'Автоматическая калитка WMD‑06, музей железных дорог России, Санкт-Петербург',
        'gallery_slide15': 'Автоматическая калитка WMD‑06, главный офис компании JYSK,Брабранд, Дания',
        'about': 'Почему PERCo',
        'about1': '  PERCo - ведущий российский производитель систем и оборудования безопасности.\nPERCo разрабатывает и выпускает: шлагбаумы, турникеты, замки, контроллеры и считыватели, системы контроля доступа.\n',
        'about2': 'PERCo - ведущий российский производитель систем и оборудования безопасности\nPERCo разрабатывает и выпускает:\n',
        'aboutli1': 'шлагбаумы',
        'aboutli2': 'турникеты',
        'aboutli3': 'замки',
        'aboutli4': 'контроллеры и считыватели',
        'aboutli5': 'системы контроля доступа',
        'icon-about-1': '33 года работы на рынке',
        'icon-about-2': 'Разветвленная дилерская сеть, сервисные центры во всех регионах России',
        'icon-about-3': 'Продажи в 92 странах мира',
        'icon-about-4': 'Склады готовой продукции в Москве, Санкт‑Петербурге, Пскове и ЕС',
        'icon-about-5': '5-летний гарантийный срок на оборудование',
        'icon-about-6': 'Техническая поддержка и бесплатное обучение в Учебном центре',
        'headquarters': 'Главный офис PERCo',
        'manufacturing_plant': 'Завод PERCo',
        'contact_us': 'Напишите нам',
        'contact_us_name': 'Имя*',
        'contact_us_company': 'Компания',
        'contact_us_phone': 'Телефон',
        'contact_us_e-mail': 'Email*',
        'contact_us_message': 'Сообщение',
        'contact_us_privacy_policy1': ' Я прочитал(а) ',
        'contact_us_privacy_policy2': ' политику конфиденциальности',
        'contact_us_privacy_policy3': ' и соглас(на)ен на обработку данных ',
        'contact_us_send': 'Отправить',
        'contact': 'Контакты',
        'mm_advantages': 'Преимущества',
        'mm_products': 'Продукция',
        'mm_gallery': 'Фотогалерея',
        'mm_about': 'О компании',
        'mm_write-us': 'Обратная связь',
        'mm_contacts': 'Контакты',
    },
    'en': {
        'advantages': 'Advantages',
        'products': 'Products',
        'gallery': 'Gallery',
        'about_us': 'About Us',
        'speed_gates': 'Speed gates',
        'hero_slide1': 'Solution for business centers',
        'hero_slide2': 'Solution for office buildings',
        'hero_slide3': 'Solution for sports and entertainment facilities',
        'hero_slide4': 'Solution for educational institutions',
        'hero_slide5': 'Solution for transportation facilities',
        'hero_slide6': 'Solution for banks',
        'advantages': 'Advantages',
        'touch_free': 'Touch-free',
        'safe_passage': 'Safe passage with children',
        'passage_of_people': 'Passage of people with reduced mobility',
        'safety_in_case': 'Safety in case of an emergency',
        'convenient_luggage': 'Convenient luggage transportation',
        '5_years_of_warranty': '5 years of warranty',
        'st-01_speed_gate': 'ST-01 Speed gate',
        'st-11_speed_gate': 'ST-11 Speed gate',
        'st-02_speed_gate': 'ST-02 Speed gate',
        'wmd-06_swing_gate': 'WMD-06 Motorized swing gate, BH-06 Tempered glass railing  ',
        'prod_slide0__text': 'ST-01 Speed gate',
        'prod_slide0__subtext': 'Multi-purpose speed gate with swing panels',
        'prod_slide1__text': 'ST-11 Speed gate',
        'prod_slide1__subtext': 'Compact speed gate with swing panels',
        'prod_slide2__text': 'ST-02 Speed gate',
        'prod_slide2__subtext': 'Speed gate with sliding panels',
        'prod_slide3__text': 'WMD-06 Swing gate',
        'prod_slide3__subtext': 'Motorized swing gate with tempered glass swing panel',
        'prod_slide4__text': 'BH-06 Railing',
        'prod_slide4__subtext': 'Tempered glass railing',
        'sublist_prod_1': 'Multi-purpose speed gate with swing panels',
        'sublist_prod_2': 'Compact speed gate with swing panels',
        'sublist_prod_3': 'Speed gate with sliding panels',
        'sublist_prod_4': 'Swing gate and railing',
        'watch_video': 'VIDEO',
        'overview': 'Overview',
        'access': 'Access',
        'dimensions': 'Dimensions',
        'safety': 'Safety',
        'design': 'Design',
        'integration': 'Integration',
        'installation_of_additional': 'Installation of additional equipment',
        'dop_slide0__name': 'Biometric readers',
        'dop_slide1__name': 'Pyrometer',
        'dop_slide2__name': 'Suprema face recognition terminal',
        'dop_slide3__name': 'ZKTeco face recognition terminal',
        'dop_slide4__name': 'Barcode',
        'dop_slide5__name': 'Card capture reader',
        'dop_slide0__signature': ' ',
        'dop_slide1__signature': 'Pyrometer',
        'dop_slide2__signature': 'Bracket for Suprema face recognition terminal',
        'dop_slide3__signature': 'ZKTeco face recognition terminal',
        'dop_slide4__signature': 'The front panel with built-in card capture reader',
        'dop_slide5__signature': 'The front panel with barcode scanner',
        'gallery': 'Gallery',
        'gallery_slide1': 'ST-01 Speed gates, Latécoère company office, France',
        'gallery_slide2': 'ST-01 Speed gates, The Cinamon Kosmos Cinema, Estonia',
        'gallery_slide3': 'ST-01 Speed gates, Emlyon Business School, France',
        'gallery_slide4': 'ST-01 Speed gates, SOK coworking space, Russia',
        'gallery_slide5': '',
        'gallery_slide6': 'ST-01 Speed gates, West-East business center, Russia',
        'gallery_slide7': '',
        'gallery_slide8': 'ST-01 Speed gates, L\'Appart Fitness, France',
        'gallery_slide9': 'ST-01 Speed gates, Student Loans company office, Scotland',
        'gallery_slide10': 'ST-01 Speed gates, PepsiCo company office, Mexico',
        'gallery_slide11': 'ST-01 Speed gates, Residential complex, Russia',
        'gallery_slide12': 'ST-01 Speed gates and WMD-06 Swing gates, Nazarbaev University, Kazakhstan',
        'gallery_slide13': 'WMD-06 swing gates, KABONK Amusement Park, the Netherlands',
        'gallery_slide14': 'WMD-06 Motorized swing gate, The Railway Museum, Russia',
        'gallery_slide15': 'WMD-06 Motorized swing gate, JYSK Headquarters, Denmark',
        'about': 'About PERCo',
        'about1': 'PERCo is a leading Russian manufacturer of security systems and equipment.\nPERCo develops and manufactures turnstiles, boom barriers, locks, controllers, readers, and access control systems.\n',
        'about2': 'PERCo is a leading Russian manufacturer of security systems and equipment.\nPERCo develops:\n',
        'aboutli1': 'boom barriers',
        'aboutli2': 'turnstiles',
        'aboutli3': 'locks',
        'aboutli4': 'controllers and readers',
        'aboutli5': 'access control systems',
        'icon-about-1': '33 years in the security market',
        'icon-about-2': 'Extensive dealer network',
        'icon-about-3': 'Export to 92 countries worldwide',
        'icon-about-4': 'Warehouses in Russia and EU (The Netherlands and Estonia)',
        'icon-about-5': 'Warranty period - 5 years',
        'icon-about-6': 'Technical support and training',
        'headquarters': 'PERCo Headquarters',
        'manufacturing_plant': 'PERCo manufacturing plant',
        'contact_us': 'Contact us',
        'contact_us_name': 'Name*',
        'contact_us_company': 'Company',
        'contact_us_phone': 'Phone',
        'contact_us_e-mail': 'E-mail*',
        'contact_us_message': 'Message',
        'contact_us_privacy_policy1': 'I have read the ',
        'contact_us_privacy_policy2': 'Privacy Policy',
        'contact_us_privacy_policy3': ' and agree to processing of my personal data.',
        'contact_us_send': 'Send',
        'contact': 'Contacts',
        'mm_advantages': 'Advantages',
        'mm_products': 'Products',
        'mm_gallery': 'Gallery',
        'mm_about': 'About Us',
        'mm_write-us': 'Contact us',
        'mm_contacts': 'Contacts',
    },
};