export default {
    'ru': {
        'page_title': 'Скоростные проходы PERCo',
        'advantages': 'Преимущества',
        'products': 'Продукция',
        'gallery': 'Фотогалерея',
        'about_us': 'О компании',
        'speed_gates': 'Скоростные проходы',
        'hero_slide1': 'Решение для бизнес-центров',
        'hero_slide2': 'Решение для офисов',
        'hero_slide3': 'Решение для спортивно-развлекательных объектов',
        'hero_slide4': 'Решение для учебных заведений',
        'hero_slide5': 'Решение для транспортных объектов',
        'hero_slide6': 'Решение для банков',
        'advantages': 'Преимущества',
        'touch_free': 'Бесконтактность',
        'safe_passage': 'Безопасность прохода с детьми',
        'passage_of_people': 'Проезд маломобильных групп населения',
        'safety_in_case': 'Безопасность в аварийной ситуации',
        'convenient_luggage': 'Комфортный провоз багажа',
        '5_years_of_warranty': '5 лет гарантии',
        'st-01_speed_gate': 'Скоростной проход ST‑01',
        'st-11_speed_gate': 'Скоростной проход ST‑11',
        'st-02_speed_gate': 'Скоростной проход ST‑02',
        'wmd-06_swing_gate': 'Калитка WMD‑06, ограждение ВН06',
        'prod_slide0__text': 'Скоростной проход ST‑01',
        'prod_slide0__subtext': 'Универсальный скоростной проход с распашными створками',
        'prod_slide1__text': 'Скоростной проход ST‑11',
        'prod_slide1__subtext': 'Компактный скоростной проход с распашными створками',
        'prod_slide2__text': 'Скоростной проход ST‑02',
        'prod_slide2__subtext': 'Скоростной проход с раздвижными створками',
        'prod_slide3__text': 'Калитка WMD‑06',
        'prod_slide3__subtext': 'Автоматическая калитка со створкой из закаленного стекла',
        'prod_slide4__text': 'Ограждение ВН06',
        'prod_slide4__subtext': 'Ограждение из закаленного стекла',
        'sublist_prod_1': 'Универсальный скоростной проход с распашными створками',
        'sublist_prod_2': 'Компактный скоростной проход с распашными створками',
        'sublist_prod_3': 'Скоростной проход с раздвижными створками',
        'sublist_prod_4': 'Калитка и ограждение',
        'operating_voltage': 'напряжение питания',
        'emergency_exit': 'аварийный выход',
        'persons-min': 'человек в минуту',
        'temperature_range': 'диапазон температур',
        'ip_rating': 'степень защиты',
        'watch_video': 'смотреть видео',
        'overview': 'Ракурсы',
        'access': 'Доступ',
        'dimensions': 'Габариты',
        'safety': 'Безопасность',
        'design': 'Исполнение',
        'integration': 'Интеграция',
        'installation_of_additional': 'Установка дополнительного оборудования',
        'dop_slide0__name': 'Биометрические считыватели',
        'dop_slide1__name': 'Пирометр',
        'dop_slide2__name': 'Терминал распознавания лиц Suprema',
        'dop_slide3__name': 'Терминал распознавания лиц ZKTeco',
        'dop_slide4__name': 'Штрихкод',
        'dop_slide5__name': 'Картоприемник',
        'dop_slide0__signature': 'Кронштейн для биометрических считывателей ',
        'dop_slide1__signature': 'Пирометр',
        'dop_slide2__signature': 'Кронштейны для терминалов распознавания лиц Suprema',
        'dop_slide3__signature': 'Терминал распознавания лиц ZKTeco',
        'dop_slide4__signature': 'Стойка для сканера штрихкода',
        'dop_slide5__signature': 'Стойка с картоприемником',
        'gallery': 'Фотогалерея',
        'gallery_slide1': 'Скоростные проходы ST‑01, офис компании Latécoère, Франция',
        'gallery_slide2': 'Скоростные проходы ST‑01, кинотеатр Cinamon Kosmos, Эстония',
        'gallery_slide3': 'Скоростные проходы ST‑01, бизнес-школа Emlyon, Франция',
        'gallery_slide4': 'Скоростные проходы ST‑01, коворкинг SOK, Москва',
        'gallery_slide5': '',
        'gallery_slide6': 'Скоростные проходы ST‑01 в составе системы контроля доступа PERCo, бизнес-центр West East, Одинцово, Московская область',
        'gallery_slide7': '',
        'gallery_slide8': 'Скоростные проходы ST‑01, фитнес-клуб L\'Appart Fitness, Франция',
        'gallery_slide9': 'Скоростные проходы ST‑01, офис компании Student Loans Company, Шотландия',
        'gallery_slide10': 'Скоростные проходы ST‑01, офис компании PepsiCo, Мексика',
        'gallery_slide11': 'Скоростные проходы ST‑01, жилой комплекс «Мосфильмовский», Москва',
        'gallery_slide12': 'Скоростные проходы ST‑01 и калитки WMD‑06, Назарбаев Университет, Нур-Султан',
        'gallery_slide13': 'Калитки WMD‑06, детский игровой комплекс KABONK, Нидерланды',
        'gallery_slide14': 'Автоматическая калитка WMD‑06, музей железных дорог России, Санкт-Петербург',
        'gallery_slide15': 'Автоматическая калитка WMD‑06, главный офис компании JYSK,Брабранд, Дания',
        'about': 'Почему PERCo',
        'about1': '  PERCo - ведущий российский производитель систем и оборудования безопасности.\nPERCo разрабатывает и выпускает: шлагбаумы, турникеты, замки, контроллеры и считыватели, системы контроля доступа.\n',
        'about2': 'PERCo - ведущий российский производитель систем и оборудования безопасности\nPERCo разрабатывает и выпускает:\n',
        'aboutli1': 'шлагбаумы',
        'aboutli2': 'турникеты',
        'aboutli3': 'замки',
        'aboutli4': 'контроллеры и считыватели',
        'aboutli5': 'системы контроля доступа',
        'icon-about-1': '34 года работы на рынке',
        'icon-about-2': 'Разветвленная дилерская сеть, сервисные центры во всех регионах России',
        'icon-about-3': 'Продажи в 92 странах мира',
        'icon-about-4': 'Склады готовой продукции в Москве, Санкт‑Петербурге, Пскове и ЕС',
        'icon-about-5': '5-летний гарантийный срок на оборудование',
        'icon-about-6': 'Техническая поддержка и бесплатное обучение в Учебном центре',
        'headquarters': 'Главный офис PERCo',
        'manufacturing_plant': 'Завод PERCo',
        'contact_us': 'Напишите нам',
        'contact_us_name': 'Имя*',
        'contact_us_company': 'Компания',
        'contact_us_phone': 'Телефон',
        'contact_us_e-mail': 'Email*',
        'contact_us_message': 'Сообщение',
        'contact_us_privacy_policy1': ' Я прочитал(а) ',
        'contact_us_privacy_policy2': ' политику конфиденциальности',
        'contact_us_privacy_policy3': ' и соглас(на)ен на обработку данных ',
        'contact_us_send': 'Отправить',
        'contact': 'Контакты',
        'mm_advantages': 'Преимущества',
        'mm_products': 'Продукция',
        'mm_gallery': 'Фотогалерея',
        'mm_about': 'О компании',
        'mm_write-us': 'Обратная связь',
        'mm_contacts': 'Контакты',
        'thanks': 'Спасибо!',
        'message_sent': 'Ваше сообщение\nотправлено',
    },
    'en': {
        'page_title': 'Speed gates PERCo',
        'advantages': 'Advantages',
        'products': 'Products',
        'gallery': 'Gallery',
        'about_us': 'About Us',
        'speed_gates': 'Speed gates',
        'hero_slide1': 'Solution for business centers',
        'hero_slide2': 'Solution for office buildings',
        'hero_slide3': 'Solution for sports and entertainment facilities',
        'hero_slide4': 'Solution for educational institutions',
        'hero_slide5': 'Solution for transportation facilities',
        'hero_slide6': 'Solution for banks',
        'advantages': 'Advantages',
        'touch_free': 'Touch-free',
        'safe_passage': 'Safe passage with children',
        'passage_of_people': 'Passage of people with reduced mobility',
        'safety_in_case': 'Safety in case of an emergency',
        'convenient_luggage': 'Convenient luggage transportation',
        '5_years_of_warranty': '5 years of warranty',
        'st-01_speed_gate': 'ST‑01 Speed gate',
        'st-11_speed_gate': 'ST‑11 Speed gate',
        'st-02_speed_gate': 'ST‑02 Speed gate',
        'wmd-06_swing_gate': 'WMD‑06 Motorized swing gate, BH‑06 Tempered glass railing',
        'prod_slide0__text': 'ST‑01 Speed gate',
        'prod_slide0__subtext': 'Multi-purpose speed gate with swing panels',
        'prod_slide1__text': 'ST‑11 Speed gate',
        'prod_slide1__subtext': 'Compact speed gate with swing panels',
        'prod_slide2__text': 'ST‑02 Speed gate',
        'prod_slide2__subtext': 'Speed gate with sliding panels',
        'prod_slide3__text': 'WMD‑06 Swing gate',
        'prod_slide3__subtext': 'Motorized swing gate with tempered glass swing panel',
        'prod_slide4__text': 'BH‑06 Railing',
        'prod_slide4__subtext': 'Tempered glass railing',
        'operating_voltage': 'operating voltage',
        'emergency_exit': 'emergency exit',
        'persons-min': 'persons/min',
        'temperature_range': 'temperature range',
        'ip_rating': 'IP rating',
        'sublist_prod_1': 'Multi-purpose speed gate with swing panels',
        'sublist_prod_2': 'Compact speed gate with swing panels',
        'sublist_prod_3': 'Speed gate with sliding panels',
        'sublist_prod_4': 'Swing gate and railing',
        'watch_video': 'VIDEO',
        'overview': 'Overview',
        'access': 'Access',
        'dimensions': 'Dimensions',
        'safety': 'Safety',
        'design': 'Design',
        'integration': 'Integration',
        'installation_of_additional': 'Installation of additional equipment',
        'dop_slide0__name': 'Biometric readers',
        'dop_slide1__name': 'Pyrometer',
        'dop_slide2__name': 'Suprema face recognition terminal',
        'dop_slide3__name': 'ZKTeco face recognition terminal',
        'dop_slide4__name': 'Barcode',
        'dop_slide5__name': 'Card capture reader',
        'dop_slide0__signature': 'Bracket for biometric readers',
        'dop_slide1__signature': 'Pyrometer',
        'dop_slide2__signature': 'Bracket for Suprema face recognition terminal',
        'dop_slide3__signature': 'ZKTeco face recognition terminal',
        'dop_slide4__signature': 'The front panel with built-in card capture reader',
        'dop_slide5__signature': 'The front panel with barcode scanner',
        'gallery': 'Gallery',
        'gallery_slide1': 'ST‑01 Speed gates, Latécoère company office, France',
        'gallery_slide2': 'ST‑01 Speed gates, The Cinamon Kosmos Cinema, Estonia',
        'gallery_slide3': 'ST‑01 Speed gates, Emlyon Business School, France',
        'gallery_slide4': 'ST‑01 Speed gates, SOK coworking space, Russia',
        'gallery_slide5': '',
        'gallery_slide6': 'ST‑01 Speed gates, West-East business center, Russia',
        'gallery_slide7': '',
        'gallery_slide8': 'ST‑01 Speed gates, L\'Appart Fitness, France',
        'gallery_slide9': 'ST‑01 Speed gates, Student Loans company office, Scotland',
        'gallery_slide10': 'ST‑01 Speed gates, PepsiCo company office, Mexico',
        'gallery_slide11': 'ST‑01 Speed gates, Residential complex, Russia',
        'gallery_slide12': 'ST‑01 Speed gates and WMD‑06 Swing gates, Nazarbaev University, Kazakhstan',
        'gallery_slide13': 'WMD‑06 Swing gates, KABONK Amusement Park, the Netherlands',
        'gallery_slide14': 'WMD‑06 Motorized swing gate, The Railway Museum, Russia',
        'gallery_slide15': 'WMD‑06 Motorized swing gate, JYSK Headquarters, Denmark',
        'about': 'About PERCo',
        'about1': 'PERCo is a leading Russian manufacturer of security systems and equipment.\nPERCo develops and manufactures turnstiles, boom barriers, locks, controllers, readers, and access control systems.\n',
        'about2': 'PERCo is a leading Russian manufacturer of security systems and equipment.\nPERCo develops:\n',
        'aboutli1': 'boom barriers',
        'aboutli2': 'turnstiles',
        'aboutli3': 'locks',
        'aboutli4': 'controllers and readers',
        'aboutli5': 'access control systems',
        'icon-about-1': '34 years in the security market',
        'icon-about-2': 'Extensive dealer network',
        'icon-about-3': 'Export to 92 countries worldwide',
        'icon-about-4': 'Warehouses in Russia and EU (The Netherlands and Estonia)',
        'icon-about-5': 'Warranty period - 5 years',
        'icon-about-6': 'Technical support and training',
        'headquarters': 'PERCo Headquarters',
        'manufacturing_plant': 'PERCo Manufacturing plant',
        'contact_us': 'Contact us',
        'contact_us_name': 'Name*',
        'contact_us_company': 'Company',
        'contact_us_phone': 'Phone',
        'contact_us_e-mail': 'E-mail*',
        'contact_us_message': 'Message',
        'contact_us_privacy_policy1': 'I have read the ',
        'contact_us_privacy_policy2': 'Privacy Policy',
        'contact_us_privacy_policy3': ' and agree to processing of my personal data.',
        'contact_us_send': 'Send',
        'contact': 'Contacts',
        'mm_advantages': 'Advantages',
        'mm_products': 'Products',
        'mm_gallery': 'Gallery',
        'mm_about': 'About Us',
        'mm_write-us': 'Contact us',
        'mm_contacts': 'Contacts',
        'thanks': 'Thank you!',
        'message_sent': 'Your message has been sent',
    },
    'sg': {
        'page_title': 'Speed gates PERCo',
        'advantages': 'Advantages',
        'products': 'Products',
        'gallery': 'Gallery',
        'about_us': 'About Us',
        'speed_gates': 'Speed gates',
        'hero_slide1': 'Solution for business centers',
        'hero_slide2': 'Solution for office buildings',
        'hero_slide3': 'Solution for sports and entertainment facilities',
        'hero_slide4': 'Solution for educational institutions',
        'hero_slide5': 'Solution for transportation facilities',
        'hero_slide6': 'Solution for banks',
        'advantages': 'Advantages',
        'touch_free': 'Touch-free',
        'safe_passage': 'Safe passage with children',
        'passage_of_people': 'Passage of people with reduced mobility',
        'safety_in_case': 'Safety in case of an emergency',
        'convenient_luggage': 'Convenient luggage transportation',
        '5_years_of_warranty': '5 years of warranty',
        'st-01_speed_gate': 'ST‑01 Speed gate',
        'st-11_speed_gate': 'ST‑11 Speed gate',
        'st-02_speed_gate': 'ST‑02 Speed gate',
        'wmd-06_swing_gate': 'WMD‑06 Motorized swing gate, BH‑06 Tempered glass railing',
        'prod_slide0__text': 'ST‑01 Speed gate',
        'prod_slide0__subtext': 'Multi-purpose speed gate with swing panels',
        'prod_slide1__text': 'ST‑11 Speed gate',
        'prod_slide1__subtext': 'Compact speed gate with swing panels',
        'prod_slide2__text': 'ST‑02 Speed gate',
        'prod_slide2__subtext': 'Speed gate with sliding panels',
        'prod_slide3__text': 'WMD‑06 Swing gate',
        'prod_slide3__subtext': 'Motorized swing gate with tempered glass swing panel',
        'prod_slide4__text': 'BH‑06 Railing',
        'prod_slide4__subtext': 'Tempered glass railing',
        'operating_voltage': 'operating voltage',
        'emergency_exit': 'emergency exit',
        'persons-min': 'persons/min',
        'temperature_range': 'temperature range',
        'ip_rating': 'IP rating',
        'sublist_prod_1': 'Multi-purpose speed gate with swing panels',
        'sublist_prod_2': 'Compact speed gate with swing panels',
        'sublist_prod_3': 'Speed gate with sliding panels',
        'sublist_prod_4': 'Swing gate and railing',
        'watch_video': 'VIDEO',
        'overview': 'Overview',
        'access': 'Access',
        'dimensions': 'Dimensions',
        'safety': 'Safety',
        'design': 'Design',
        'integration': 'Integration',
        'installation_of_additional': 'Installation of additional equipment',
        'dop_slide0__name': 'Biometric readers',
        'dop_slide1__name': 'Pyrometer',
        'dop_slide2__name': 'Suprema face recognition terminal',
        'dop_slide3__name': 'ZKTeco face recognition terminal',
        'dop_slide4__name': 'Barcode',
        'dop_slide5__name': 'Card capture reader',
        'dop_slide0__signature': 'Bracket for biometric readers',
        'dop_slide1__signature': 'Pyrometer',
        'dop_slide2__signature': 'Bracket for Suprema face recognition terminal',
        'dop_slide3__signature': 'ZKTeco face recognition terminal',
        'dop_slide4__signature': 'The front panel with built-in card capture reader',
        'dop_slide5__signature': 'The front panel with barcode scanner',
        'gallery': 'Gallery',
        'gallery_slide1': 'ST‑01 Speed gates, Latécoère company office, France',
        'gallery_slide2': 'ST‑01 Speed gates, The Cinamon Kosmos Cinema, Estonia',
        'gallery_slide3': 'ST‑01 Speed gates, Emlyon Business School, France',
        'gallery_slide4': 'ST‑01 Speed gates, SOK coworking space',
        'gallery_slide5': '',
        'gallery_slide6': 'ST‑01 Speed gates, West-East business center',
        'gallery_slide7': '',
        'gallery_slide8': 'ST‑01 Speed gates, L\'Appart Fitness, France',
        'gallery_slide9': 'ST‑01 Speed gates, Student Loans company office, Scotland',
        'gallery_slide10': 'ST‑01 Speed gates, PepsiCo company office, Mexico',
        'gallery_slide11': 'ST‑01 Speed gates, Residential complex',
        'gallery_slide12': 'ST‑01 Speed gates and WMD‑06 Swing gates, Nazarbaev University, Kazakhstan',
        'gallery_slide13': 'WMD‑06 Swing gates, KABONK Amusement Park, the Netherlands',
        'gallery_slide14': 'WMD‑06 Motorized swing gate, The Railway Museum',
        'gallery_slide15': 'WMD‑06 Motorized swing gate, JYSK Headquarters, Denmark',
        'about': 'About PERCo',
        'about1': 'PERCo is a leading Russian manufacturer of security systems and equipment.\nPERCo develops and manufactures turnstiles, boom barriers, locks, controllers, readers, and access control systems.\n',
        'about2': 'PERCo is a leading Russian manufacturer of security systems and equipment.\nPERCo develops:\n',
        'aboutli1': 'boom barriers',
        'aboutli2': 'turnstiles',
        'aboutli3': 'locks',
        'aboutli4': 'controllers and readers',
        'aboutli5': 'access control systems',
        'icon-about-1': '34 years in the security market',
        'icon-about-2': 'Extensive dealer network',
        'icon-about-3': 'Export to 92 countries worldwide',
        'icon-about-4': 'Warehouses in Russia and EU (The Netherlands and Estonia)',
        'icon-about-5': 'Warranty period - 5 years',
        'icon-about-6': 'Technical support and training',
        'headquarters': 'PERCo Headquarters',
        'manufacturing_plant': 'PERCo Manufacturing plant',
        'contact_us': 'Contact us',
        'contact_us_name': 'Name*',
        'contact_us_company': 'Company',
        'contact_us_phone': 'Phone',
        'contact_us_e-mail': 'E-mail*',
        'contact_us_message': 'Message',
        'contact_us_privacy_policy1': 'I have read the ',
        'contact_us_privacy_policy2': 'Privacy Policy',
        'contact_us_privacy_policy3': ' and agree to processing of my personal data.',
        'contact_us_send': 'Send',
        'contact': 'Contacts',
        'mm_advantages': 'Advantages',
        'mm_products': 'Products',
        'mm_gallery': 'Gallery',
        'mm_about': 'About Us',
        'mm_write-us': 'Contact us',
        'mm_contacts': 'Contacts',
        'thanks': 'Thank you!',
        'message_sent': 'Your message has been sent',
    },
    'fr': {
        'page_title': 'Couloirs de contrôle d’accès PERCo',
        'advantages': 'Avantages',
        'products': 'Produits',
        'gallery': 'Galerie photos',
        'about_us': 'La société',
        'speed_gates': 'Couloirs de contrôle d’accès',
        'hero_slide1': 'Solutions pour centres d’affaires',
        'hero_slide2': 'Solutions pour bureau et sièges sociaux',
        'hero_slide3': 'Solutions pour centres sportifs et culturels',
        'hero_slide4': 'Solutions pour établissements d’enseignement',
        'hero_slide5': 'Solutions pour bâtiments logistiques',
        'hero_slide6': 'Solution pour établissements bancaires',
        'advantages': 'Avantages',
        'touch_free': 'Solution sans contact',
        'safe_passage': 'Passage sécurisé pour les enfants',
        'passage_of_people': 'Passage pour personnes à mobilité réduite',
        'safety_in_case': 'Sécurité en cas d’urgence',
        'convenient_luggage': 'Transport des bagages aisé',
        '5_years_of_warranty': '5années de garantie',
        'st-01_speed_gate': 'Couloir rapide ST-01',
        'st-11_speed_gate': 'Couloir rapide ST-11',
        'st-02_speed_gate': 'Couloir rapide ST-02',
        'wmd-06_swing_gate': 'Portillon pivotant motorisé WMD-06, garde-corps en verre trempé BH-06',
        'prod_slide0__text': 'Couloir rapide ST-01',
        'prod_slide0__subtext': 'Couloir rapide de contrôle d’accès à vantaux battants multiusage',
        'prod_slide1__text': 'Couloir rapide ST-11',
        'prod_slide1__subtext': 'Couloir rapide compact à vantaux battants',
        'prod_slide2__text': 'Couloir rapide ST-02',
        'prod_slide2__subtext': 'Couloir rapide compact à vantaux coulissants',
        'prod_slide3__text': 'Portillon pivotant WMD-06',
        'prod_slide3__subtext': 'Portillon pivotant motorisé avec vantail en verre trempé',
        'prod_slide4__text': 'Garde-corps BH-06',
        'prod_slide4__subtext': 'Garde-corps en verre trempé',
        'operating_voltage': 'operating voltage',
        'emergency_exit': 'emergency exit',
        'persons-min': 'persons/min',
        'temperature_range': 'temperature range',
        'ip_rating': 'IP rating',
        'sublist_prod_1': 'Couloir rapide de contrôle d’accès à vantaux battants multiusage',
        'sublist_prod_2': 'Couloir rapide compact à vantaux battants',
        'sublist_prod_3': 'Couloir rapide à vantaux coulissants',
        'sublist_prod_4': 'Portillon pivotant et garde-corps',
        'watch_video': 'VIDEO',
        'overview': 'Vue d’ensemble',
        'access': 'Accès',
        'dimensions': 'Dimensions',
        'safety': 'Sécurité',
        'design': 'Design',
        'integration': 'Integration',
        'installation_of_additional': 'Installation d’équipements additionnels',
        'dop_slide0__name': 'Terminaux biométriques',
        'dop_slide1__name': 'Capteur de temperature',
        'dop_slide2__name': 'Terminal de reconnaissance faciale Suprema',
        'dop_slide3__name': 'Terminal de reconnaissance faciale ZKTeco',
        'dop_slide4__name': 'Code barre',
        'dop_slide5__name': 'Lecteur de carte avec avaleur',
        'dop_slide0__signature': 'Support pour lecteurs biométriques',
        'dop_slide1__signature': 'Capteur de température',
        'dop_slide2__signature': 'Support pour terminal de reconnaissance faciale Suprema',
        'dop_slide3__signature': 'Terminal de reconnaissance faciale ZKTeco',
        'dop_slide4__signature': 'Façade avec lecteur de carte et avaleur',
        'dop_slide5__signature': 'Façade avec scanner de code barre',
        'gallery': 'Galerie photos',
        'gallery_slide1': 'Couloirs rapides ST-01, siege social Latécoère, France',
        'gallery_slide2': 'Couloirs rapides ST-01, cinéma The Cinamon Kosmos, Estonie',
        'gallery_slide3': 'Couloirs rapides ST-01, Business School EmLyon, France',
        'gallery_slide4': 'Couloirs rapides ST-01, espace de coworking, Russie',
        'gallery_slide5': '',
        'gallery_slide6': 'Couloirs rapides ST-01, centre d’affaires West-East, Russie',
        'gallery_slide7': '',
        'gallery_slide8': 'Couloirs rapides ST-01, L’Appart Fitness, France',
        'gallery_slide9': 'Couloirs rapides ST-01, société de prêts aux étudiants, Ecosse',
        'gallery_slide10': 'Couloirs rapides ST-01, bureaux société PepsiCo, Mexico',
        'gallery_slide11': 'Couloirs rapides ST-01, complexe residential, Russie',
        'gallery_slide12': 'Couloirs rapides ST-01 et portillons pivotants WMD-06, Université Nazarbaev, Kazakhstan',
        'gallery_slide13': 'Portillons pivotants WMD-06, parc d’attractions, Hollande',
        'gallery_slide14': 'Portillons pivotants WMD-06, Musée du rail, Russie',
        'gallery_slide15': 'Portillons pivotants WMD-06, sige social JYSK, Danemark',
        'about': 'A propos de PERCo',
        'about1': 'PERCo est un leader russe de la fabrication d’équipements et systèmes de sécurité.\nPERco conçoit et fabrique des tourniquets, des barriers levantes, des serrures, des contrôleurs, des lecteurs et des systèmes de contrôle d’accès.\n',
        'about2': 'PERCo est un leader russe de la fabrication d’équipements et systèmes de sécurité.\nPERco conçoit et fabrique:\n',
        'aboutli1': 'des tourniquets',
        'aboutli2': 'des barriers levantes',
        'aboutli3': 'des serrures',
        'aboutli4': 'des contrôleurs',
        'aboutli5': 'des lecteurs et des systèmes de contrôle d’accès',
        'icon-about-1': '34 années d’expérience sur le marché de la sécurité',
        'icon-about-2': 'Un réseau de revendeurs étendu',
        'icon-about-3': 'Des exportations dans 92 pays partout dans le monde',
        'icon-about-4': 'Des stocks centraux en Russie et en Estonie',
        'icon-about-5': '5 années de garantie',
        'icon-about-6': 'Des formations et un support technique',
        'headquarters': 'Siège social PERCo',
        'manufacturing_plant': 'Usine PERCo',
        'contact_us': 'Contactez-nous',
        'contact_us_name': 'Nom*',
        'contact_us_company': 'Société',
        'contact_us_phone': 'Tél',
        'contact_us_e-mail': 'E-mail*',
        'contact_us_message': 'Message',
        'contact_us_privacy_policy1': 'J’ai lu la ',
        'contact_us_privacy_policy2': 'Politique de confidentialité',
        'contact_us_privacy_policy3': ' et j’accepte le traitement de mes données personnelles.',
        'contact_us_send': 'Envoyer',
        'contact': 'Contacts',
        'mm_advantages': 'Avantages',
        'mm_products': 'Produits',
        'mm_gallery': 'Galerie photos',
        'mm_about': 'La société',
        'mm_write-us': 'Contactez-nous',
        'mm_contacts': 'Contacts',
        'thanks': 'Merci !',
        'message_sent': 'Votre message a été envoyé',
    },
};